routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;
// Standard laravel page
Route::get('/', 'Blog\PostController@index');

//Routes for login/logout
Auth::routes();

//home page
Route::get('/home', 'HomeController@index')->name('home');

//Admin panel main page
Route::get('/admin/blog', 'Blog\Admin\AdminController@index')->middleware('is_admin')->name('blog.admin');

//Posts page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('posts', 'PostController')->only('index', 'show')->names('post.blog');
});

//Category page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('categories', 'CategoryController')
        ->only('index', 'show')
        ->names('post.categories');
});

//Author page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('authors', 'AuthorController')
        ->only('index', 'show')
        ->names('post.authors');
});
//Admin panel posts and categories pages
$groupData = [
    'namespace' => 'Blog\Admin',
    'prefix'    => 'admin/blog',
];
Route::group($groupData, function (){
    Route::resource('categories', 'CategoryController')->except('show')->middleware('is_admin')->names('blog.admin.categories');

    Route::resource('posts', 'PostController')->except('show')->middleware('is_admin')->names('blog.admin.posts');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if($errors->any())
                <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{$error}}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            @endif
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <h5 class="card-title">You are logged in!</h5>
                        @if(auth()->user()->isAdmin())
                        <p class="card-text">
                            <a href="{{route('blog.admin')}}">Go to admin panel</a>
                        </p>
                        @endif
                        <p class="card-text">
                            <a href="{{route('post.blog.index')}}">View all post</a><br>
                            <a href="{{route('post.categories.index')}}">View all categories</a><br>
                            <a href="{{route('post.authors.index')}}">View all authors</a><br>
                        </p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection