routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;
// Standard laravel page
Route::get('/', 'Blog\PostController@index');

//Routes for login/logout
Auth::routes();

//home page
Route::get('/home', 'HomeController@index')->name('home');

//Admin panel main page
Route::get('/admin/blog', 'Blog\Admin\AdminController@index')->middleware('is_admin')->name('blog.admin');

//Posts page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('posts', 'PostController')->only('index', 'show')->names('post.blog');
});

//Category page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('categories', 'CategoryController')
        ->only('index', 'show')
        ->names('post.categories');
});

//Author page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('authors', 'AuthorController')
        ->only('index', 'show')
        ->names('post.authors');
});
//Admin panel posts and categories pages
$groupData = [
    'namespace' => 'Blog\Admin',
    'prefix'    => 'admin/blog',
];
Route::group($groupData, function (){
    Route::resource('categories', 'CategoryController')->except('show')->middleware('is_admin')->names('blog.admin.categories');

    Route::resource('posts', 'PostController')->except('show')->middleware('is_admin')->names('blog.admin.posts');
});

app/Http/Controllers/Blog/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Repositories\BlogCategoryRepository;
use App\Models\BlogCategory;
use Illuminate\Support\Str;
use App\Http\Requests\{
    BlogCategoryCreateRequest,
    BlogCategoryUpdateRequest
};

class CategoryController extends BaseController
{
    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        parent::__construct();
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = $this->blogCategoryRepository->getAllWithPaginate(5);
        return view('blog.admin.categories.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = new BlogCategory();
        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.categories.edit', compact('item', 'categoryList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\BlogCategoryCreateRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogCategoryCreateRequest $request)
    {
        $data = $request->input();

        $item = (new BlogCategory())->create($data);

        if($item){
            return redirect()
                ->route('blog.admin.categories.edit', [$item->id])
                ->with(['Success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Failed to save'])
                ->withInput();
        }

    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $item = $this->blogCategoryRepository->getEdit($id);
        if(empty($item)){
            abort(404);
        }

        $categoryList = $this->blogCategoryRepository->getForComboBox();
        return view('blog.admin.categories.edit', compact('item', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\BlogCategoryUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogCategoryUpdateRequest $request, $id)
    {

        $item = $this->blogCategoryRepository->getEdit($id);
        if(empty($item)){
            return back()->withErrors(['msg' => 'Entity with id=[{$id}] not found'])->withInput();
        }

        $data = $request->all();

        $result = $item->update($data);

        if($result){
            return redirect()->route('blog.admin.categories.edit', $item->id)
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()->withErrors(['msg' => 'Failed to save'])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = BlogCategory::destroy($id);

        if($result){
            return redirect()
                ->route('blog.admin.categories.index')
                ->with(['success' => "Category with ID: [$id] was deleted"]);
        } else {
            return back()->withErrors(['msg' => 'Cant delete the post']);
        }
    }
}

app/Http/Controllers/Blog/CategoryController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Repositories\BlogCategoryRepository;
use App\Repositories\BlogPostRepository;

class CategoryController extends BaseController
{
    /**
     * @var BlogPostRepository
     */
    private $blogPostRepository;
    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        $this->blogPostRepository = app(BlogPostRepository::class);
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = $this->blogCategoryRepository->getAllWithPaginateAndPostQuantity(6);
        $postsPerCategory = $this->blogPostRepository->getPostsPerCategory();
        $postsPerAuthor = $this->blogPostRepository->getPostsPerAuthor();
        return view('blog.categories.index', compact('paginator', 'postsPerAuthor', 'postsPerCategory'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $paginator = $this->blogPostRepository->getCategoryPostsWithPaginate($id, 5);
        $postsPerCategory = $this->blogPostRepository->getPostsPerCategory();
        $postsPerAuthor = $this->blogPostRepository->getPostsPerAuthor();

        return view('blog.categories.category', compact('paginator', 'postsPerAuthor', 'postsPerCategory'));
    }

}

resources/views/blog/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    @php
        /** @var \App\Models\BlogCategory $item */
        /** @var \Illuminate\Support\ViewErrorBag $errors */
    @endphp
    <div class="container">
    @if($item->exists)
        <form action="{{route('blog.admin.categories.update', $item->id)}}" method="post">
        @method('PATCH')
    @else
        <form action="{{route('blog.admin.categories.store', $item->id)}}" method="post">
    @endif
        @csrf
        @if($errors->any())
            <div class="row justify-content-center">
                <div class="col-md-11">
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{$errors->first()}}
                    </div>
                </div>
            </div>
        @endif

        @if(session('success'))
            <div class="row justify-content-center">
                <div class="col-md-11">
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{session()->get('success')}}
                    </div>
                </div>
            </div>
        @endif
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('blog.admin.categories.includes.item_edit_main_col')
                    @if(! $item->exists)
                    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                        <a class="btn btn-light" href="{{route('blog.admin.categories.index')}}">&larr; Back</a>
                    </nav>
                    @endif
                </div>
                <div class="col-md-3">
                    @include('blog.admin.categories.includes.item_edit_add_col')
                </div>
            </div>
    </form>
    @if($item->exists)
        <br>
        <form action="{{route('blog.admin.categories.destroy', $item->id)}}" method="post">
            @method('DELETE')
            @csrf
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card card-block">
                        <div class="card-body nl-auto">
                            @if($item->id == 1)
                                <span>Can't delete root category</span>
                            @else
                                <button type="submit" class="btn btn-danger">DELETE</button>
                            @endif
                        </div>
                    </div>
                    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                        <a class="btn btn-light" href="{{route('blog.admin.categories.index')}}">&larr; Back</a>
                    </nav>
                </div>
                <div class="col-md-3"></div>
            </div>
        </form>
    @endif
    </div>
@endsection

resources/views/blog/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                    <a class="btn btn-light" href="{{route('blog.admin')}}">&larr; Back</a>
                    <a class="btn btn-primary" href="{{route('blog.admin.categories.create')}}">Add category</a>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                                <td>#</td>
                                <td>Category</td>
                                <td>Patent Category</td>
                            </thead>
                            <tbody>
                            @foreach($paginator as $category)
                                @php /** @var \App\Models\BlogCategory $category */@endphp
                                <tr>
                                    <td>{{$category->id}}</td>
                                    <td>
                                        <a href="{{route('blog.admin.categories.edit', $category->id)}}">
                                            {{$category->title}}
                                        </a>
                                    </td>
                                    <td @if (in_array($category->parent_id, [0,1])) style="color:#ccc;"@endif>
                                        {{$category->parentTitle}}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @if($paginator->total() > $paginator->count())
            <br>
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            {{$paginator->links() }}
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection