routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;
// Standard laravel page
Route::get('/', 'Blog\PostController@index');

//Routes for login/logout
Auth::routes();

//home page
Route::get('/home', 'HomeController@index')->name('home');

//Admin panel main page
Route::get('/admin/blog', 'Blog\Admin\AdminController@index')->middleware('is_admin')->name('blog.admin');

//Posts page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('posts', 'PostController')->only('index', 'show')->names('post.blog');
});

//Category page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('categories', 'CategoryController')
        ->only('index', 'show')
        ->names('post.categories');
});

//Author page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('authors', 'AuthorController')
        ->only('index', 'show')
        ->names('post.authors');
});
//Admin panel posts and categories pages
$groupData = [
    'namespace' => 'Blog\Admin',
    'prefix'    => 'admin/blog',
];
Route::group($groupData, function (){
    Route::resource('categories', 'CategoryController')->except('show')->middleware('is_admin')->names('blog.admin.categories');

    Route::resource('posts', 'PostController')->except('show')->middleware('is_admin')->names('blog.admin.posts');
});

app/Http/Controllers/Blog/Admin/PostController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Models\BlogPost;
use App\Repositories\BlogCategoryRepository;
use App\Repositories\BlogPostRepository;
use App\Http\Requests\BlogPostUpdateRequest;
use App\Http\Requests\BlogPostCreateRequest;

class PostController extends BaseController
{
    /**
     * @var BlogPostRepository
     */
    private $blogPostRepository;
    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        parent::__construct();
        $this->blogPostRepository = app(BlogPostRepository::class);
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = $this->blogPostRepository->getAllWithPaginate();

        return view('blog.admin.posts.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = new BlogPost();
        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.posts.edit', compact('item', 'categoryList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\BlogPostCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogPostCreateRequest $request)
    {
        $data = $request->input();
        $item = (new BlogPost())->create($data);

        if($item){
            return redirect()
                ->route('blog.admin.posts.edit', [$item->id])
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Failed to save'])
                ->withInput();
        }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = $this->blogPostRepository->getEdit($id);
        if(empty($item)){
            abort(404);
        }

        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.posts.edit', compact('item', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\BlogPostUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogPostUpdateRequest $request, $id)
    {
        $item = $this->blogPostRepository->getEdit($id);

        if(empty($item)){
            return back()
                ->withErrors(['msg' => 'Post with ID: {{$id}} not found'])
                ->withInput();
        }

        $data = $request->all();

        $result = $item->update($data);

        if($result){
            return redirect()
                ->route('blog.admin.posts.edit',$item->id)
                ->with(['success' => 'Post successfully updated']);
        } else {
            return back()
                ->withErrors(['msg' => 'Failed to update post'])
                ->withInput();
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = BlogPost::destroy($id);

        if($result){
            return redirect()
                ->route('blog.admin.posts.index')
                ->with(['success' => "Post with ID: [$id] was deleted"]);
        } else {
            return back()->withErrors(['msg' => 'Cant delete the post']);
        }
    }
}

app/Http/Controllers/Blog/PostController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Repositories\BlogCategoryRepository;
use App\Repositories\BlogPostRepository;

class PostController extends BaseController
{
    /**
     * @var BlogPostRepository
     */
    private $blogPostRepository;
    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        $this->blogPostRepository = app(BlogPostRepository::class);
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = $this->blogPostRepository->getAllPublishedWithPaginate();
        $categoryList = $this->blogCategoryRepository->getCategoryList();
        $postsPerCategory = $this->blogPostRepository->getPostsPerCategory();
        $postsPerAuthor = $this->blogPostRepository->getPostsPerAuthor();
        return view('blog.posts.index', compact('paginator', 'categoryList', 'postsPerCategory', 'postsPerAuthor'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = $this->blogPostRepository->getEdit($id);
        if(empty($item)){
            abort(404);
        }
        $postsPerCategory = $this->blogPostRepository->getPostsPerCategory();
        $postsPerAuthor = $this->blogPostRepository->getPostsPerAuthor();
        return view('blog.posts.post',compact('item','postsPerCategory', 'postsPerAuthor'));
    }
}

resources/views/blog/admin/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    @php
        /** @var \App\Models\BlogPost $item */
        /** @var \Illuminate\Support\ViewErrorBag $errors */
    @endphp
    <div class="container">
        @include('blog.admin.posts.includes.result_messages')
        @if($item->exists)
            <form action="{{route('blog.admin.posts.update', $item->id)}}" method="post">
            @method('PATCH')
        @else
            <form action="{{route('blog.admin.posts.store', $item->id)}}" method="post">
        @endif
            @csrf
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        @include('blog.admin.posts.includes.item_edit_main_col')
                        @if(!$item->exists)
                        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                            <a class="btn btn-light" href="{{route('blog.admin.posts.index')}}">&larr; Back</a>
                        </nav>
                        @endif
                    </div>
                    <div class="col-md-3">
                        @include('blog.admin.posts.includes.item_edit_add_col')
                    </div>
                </div>
            </form>
            @if($item->exists)
            <br>
            <form action="{{route('blog.admin.posts.destroy', $item->id)}}" method="post">
            @method('DELETE')
            @csrf
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card card-block">
                            <div class="card-body nl-auto">
                                <button type="submit" class="btn btn-danger">DELETE</button>
                            </div>
                        </div>
                        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                            <a class="btn btn-light" href="{{route('blog.admin.posts.index')}}">&larr; Back</a>
                        </nav>
                    </div>
                    <div class="col-md-3"></div>
                </div>
            </form>
            @endif
    </div>
@endsection

resources/views/blog/admin/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                    <a class="btn btn-light" href="{{route('blog.admin')}}">&larr; Back</a>
                    <a class="btn btn-primary" href="{{route('blog.admin.posts.create')}}">Add post</a>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                            <td>#</td>
                            <td>Author</td>
                            <td>Category</td>
                            <td>Title</td>
                            <td>Published at</td>
                            </thead>
                            <tbody>
                            @foreach($paginator as $post)
                                @php /** @var \App\Models\BlogPost $post */@endphp
                                <tr @if(!$post->is_published) style="color:#ccc" @endif>
                                    <td>{{$post->id}}</td>
                                    <td>{{$post->user->name}}</td>
                                    <td>{{$post->category->title}}</td>
                                    <td>
                                        <a href="{{route('blog.admin.posts.edit', $post->id)}}">
                                            {{$post->title}}
                                        </a>
                                    </td>
                                    <td>
                                        {{$post->published_at ? \Carbon\Carbon::parse($post->published_at)->format('Y-m-d H:i:s') : ''}}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @if($paginator->total() > $paginator->count())
            <br>
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            {{$paginator->links() }}
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection