routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;
// Standard laravel page
Route::get('/', 'Blog\PostController@index');

//Routes for login/logout
Auth::routes();

//home page
Route::get('/home', 'HomeController@index')->name('home');

//Admin panel main page
Route::get('/admin/blog', 'Blog\Admin\AdminController@index')->middleware('is_admin')->name('blog.admin');

//Posts page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('posts', 'PostController')->only('index', 'show')->names('post.blog');
});

//Category page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('categories', 'CategoryController')
        ->only('index', 'show')
        ->names('post.categories');
});

//Author page
Route::group(['namespace' => 'blog', 'prefix' => 'blog'], function(){
    Route::resource('authors', 'AuthorController')
        ->only('index', 'show')
        ->names('post.authors');
});
//Admin panel posts and categories pages
$groupData = [
    'namespace' => 'Blog\Admin',
    'prefix'    => 'admin/blog',
];
Route::group($groupData, function (){
    Route::resource('categories', 'CategoryController')->except('show')->middleware('is_admin')->names('blog.admin.categories');

    Route::resource('posts', 'PostController')->except('show')->middleware('is_admin')->names('blog.admin.posts');
});

app/Http/Controllers/Blog/Admin/AdminController.php
<?php
/**
 * Created by PhpStorm.
 * User: Slobodian
 * Date: 23.11.2019
 * Time: 17:32
 */

namespace App\Http\Controllers\Blog\Admin;


class AdminController extends BaseController
{
    public function index()
    {
        return view('blog.admin.index');
    }
}

app/Http/Controllers/Blog/Admin/BaseController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Http\Controllers\Blog\BaseController as GuestBaseController;

abstract class BaseController extends GuestBaseController
{
    /**
     * BaseController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
}

app/Http/Controllers/Blog/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Repositories\BlogCategoryRepository;
use App\Models\BlogCategory;
use Illuminate\Support\Str;
use App\Http\Requests\{
    BlogCategoryCreateRequest,
    BlogCategoryUpdateRequest
};

class CategoryController extends BaseController
{
    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        parent::__construct();
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = $this->blogCategoryRepository->getAllWithPaginate(5);
        return view('blog.admin.categories.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = new BlogCategory();
        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.categories.edit', compact('item', 'categoryList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\BlogCategoryCreateRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogCategoryCreateRequest $request)
    {
        $data = $request->input();

        $item = (new BlogCategory())->create($data);

        if($item){
            return redirect()
                ->route('blog.admin.categories.edit', [$item->id])
                ->with(['Success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Failed to save'])
                ->withInput();
        }

    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $item = $this->blogCategoryRepository->getEdit($id);
        if(empty($item)){
            abort(404);
        }

        $categoryList = $this->blogCategoryRepository->getForComboBox();
        return view('blog.admin.categories.edit', compact('item', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\BlogCategoryUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogCategoryUpdateRequest $request, $id)
    {

        $item = $this->blogCategoryRepository->getEdit($id);
        if(empty($item)){
            return back()->withErrors(['msg' => 'Entity with id=[{$id}] not found'])->withInput();
        }

        $data = $request->all();

        $result = $item->update($data);

        if($result){
            return redirect()->route('blog.admin.categories.edit', $item->id)
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()->withErrors(['msg' => 'Failed to save'])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = BlogCategory::destroy($id);

        if($result){
            return redirect()
                ->route('blog.admin.categories.index')
                ->with(['success' => "Category with ID: [$id] was deleted"]);
        } else {
            return back()->withErrors(['msg' => 'Cant delete the post']);
        }
    }
}

app/Http/Controllers/Blog/Admin/PostController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Models\BlogPost;
use App\Repositories\BlogCategoryRepository;
use App\Repositories\BlogPostRepository;
use App\Http\Requests\BlogPostUpdateRequest;
use App\Http\Requests\BlogPostCreateRequest;

class PostController extends BaseController
{
    /**
     * @var BlogPostRepository
     */
    private $blogPostRepository;
    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        parent::__construct();
        $this->blogPostRepository = app(BlogPostRepository::class);
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = $this->blogPostRepository->getAllWithPaginate();

        return view('blog.admin.posts.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = new BlogPost();
        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.posts.edit', compact('item', 'categoryList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\BlogPostCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogPostCreateRequest $request)
    {
        $data = $request->input();
        $item = (new BlogPost())->create($data);

        if($item){
            return redirect()
                ->route('blog.admin.posts.edit', [$item->id])
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Failed to save'])
                ->withInput();
        }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = $this->blogPostRepository->getEdit($id);
        if(empty($item)){
            abort(404);
        }

        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.posts.edit', compact('item', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\BlogPostUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogPostUpdateRequest $request, $id)
    {
        $item = $this->blogPostRepository->getEdit($id);

        if(empty($item)){
            return back()
                ->withErrors(['msg' => 'Post with ID: {{$id}} not found'])
                ->withInput();
        }

        $data = $request->all();

        $result = $item->update($data);

        if($result){
            return redirect()
                ->route('blog.admin.posts.edit',$item->id)
                ->with(['success' => 'Post successfully updated']);
        } else {
            return back()
                ->withErrors(['msg' => 'Failed to update post'])
                ->withInput();
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = BlogPost::destroy($id);

        if($result){
            return redirect()
                ->route('blog.admin.posts.index')
                ->with(['success' => "Post with ID: [$id] was deleted"]);
        } else {
            return back()->withErrors(['msg' => 'Cant delete the post']);
        }
    }
}

app/Http/Controllers/Blog/AuthorController.php
<?php
/**
 * Created by PhpStorm.
 * User: Slobodian
 * Date: 24.11.2019
 * Time: 19:17
 */

namespace App\Http\Controllers\Blog;

use App\Repositories\BlogCategoryRepository;
use App\Repositories\BlogPostRepository;

class AuthorController extends BaseController
{
    /**
     * @var BlogPostRepository
     */
    private $blogPostRepository;

    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        $this->blogPostRepository = app(BlogPostRepository::class);
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = $this->blogPostRepository->getAllAuthors();
        $categoryList = $this->blogCategoryRepository->getCategoryList();
        $postsPerCategory = $this->blogPostRepository->getPostsPerCategory();
        $postsPerAuthor = $this->blogPostRepository->getPostsPerAuthor();
        return view('blog.authors.index', compact('paginator', 'categoryList', 'postsPerAuthor', 'postsPerCategory'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $paginator = $this->blogPostRepository->getAuthorPostsWithPaginate($id, 5);
        $postsPerCategory = $this->blogPostRepository->getPostsPerCategory();
        $postsPerAuthor = $this->blogPostRepository->getPostsPerAuthor();

        return view('blog.authors.author', compact('paginator', 'postsPerAuthor', 'postsPerCategory'));
    }
}

app/Http/Controllers/Blog/BaseController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

abstract class BaseController extends Controller
{

}

app/Http/Controllers/Blog/CategoryController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Repositories\BlogCategoryRepository;
use App\Repositories\BlogPostRepository;

class CategoryController extends BaseController
{
    /**
     * @var BlogPostRepository
     */
    private $blogPostRepository;
    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        $this->blogPostRepository = app(BlogPostRepository::class);
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = $this->blogCategoryRepository->getAllWithPaginateAndPostQuantity(6);
        $postsPerCategory = $this->blogPostRepository->getPostsPerCategory();
        $postsPerAuthor = $this->blogPostRepository->getPostsPerAuthor();
        return view('blog.categories.index', compact('paginator', 'postsPerAuthor', 'postsPerCategory'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $paginator = $this->blogPostRepository->getCategoryPostsWithPaginate($id, 5);
        $postsPerCategory = $this->blogPostRepository->getPostsPerCategory();
        $postsPerAuthor = $this->blogPostRepository->getPostsPerAuthor();

        return view('blog.categories.category', compact('paginator', 'postsPerAuthor', 'postsPerCategory'));
    }

}

app/Http/Controllers/Blog/PostController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Repositories\BlogCategoryRepository;
use App\Repositories\BlogPostRepository;

class PostController extends BaseController
{
    /**
     * @var BlogPostRepository
     */
    private $blogPostRepository;
    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        $this->blogPostRepository = app(BlogPostRepository::class);
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = $this->blogPostRepository->getAllPublishedWithPaginate();
        $categoryList = $this->blogCategoryRepository->getCategoryList();
        $postsPerCategory = $this->blogPostRepository->getPostsPerCategory();
        $postsPerAuthor = $this->blogPostRepository->getPostsPerAuthor();
        return view('blog.posts.index', compact('paginator', 'categoryList', 'postsPerCategory', 'postsPerAuthor'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = $this->blogPostRepository->getEdit($id);
        if(empty($item)){
            abort(404);
        }
        $postsPerCategory = $this->blogPostRepository->getPostsPerCategory();
        $postsPerAuthor = $this->blogPostRepository->getPostsPerAuthor();
        return view('blog.posts.post',compact('item','postsPerCategory', 'postsPerAuthor'));
    }
}

resources/views/blog/posts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <nav class="navbar navbar-toggleable-md navbar-light bg-faded">

            </nav>

            <div class="row">
                <div class="col-md-8 mb-3">
                    <div class="row justify-content-center">
                        @foreach($paginator as $item)
                        <a href="{{route('post.blog.show',$item->id)}}" style="text-decoration: none; color: black">
                            <div class="col-md-12 mb-3">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="card-title">{{$item->title}}</h4>
                                        <h5 class="card-subtitle mb-3">{{$item->excerpt}}</h5>
                                        <p class="card-text">{{substr($item->content_html,0,255)}}...</p>
                                    </div>
                                    <div class="card-body">
                                        <p class="card-text"> Author:
                                            <a href="{{route('post.authors.show',$item->user_id)}}" class="card-link">{{$item->user->name}}</a>
                                        </p>
                                    </div>
                                    <div class="card-footer d-flex justify-content-between">
                                        <span>Category: <a href="{{route('post.categories.show',$item->category->id)}}" class="card-link">{{$item->category->title}}</a></span>
                                        <span>Published Date: {{$item->published_at}}</span>
                                    </div>
                                </div>
                            </div>
                        </a>
                        @endforeach
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row justify-content-center align-bottom mb-5">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <a href="{{route('post.categories.index')}}">All Categories</a>
                                </div>
                                <ul class="list-group list-group-flush">
                                    @foreach($categoryList as $category)
                                    <li class="list-group-item">
                                        <a href="{{route('post.categories.show',$category->id)}}">{{$category->title}}</a>
                                    </li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                    @include('blog.includes.toplist')
                </div>
            </div>
        </div>
    </div>
    @if($paginator->total() > $paginator->count())
        <br>
        <div class="row justify-content-center">
            <div class="col-md-12">
                        {{$paginator->links() }}
            </div>
        </div>
    @endif
</div>
@endsection

resources/views/blog/posts/post.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                    <a class="btn btn-light" href="{{route('post.blog.index')}}">&larr; All posts</a>
                </nav>

                <div class="row">
                    <div class="col-md-8 mb-3">
                        <div class="row justify-content-center">
                            <div class="col-md-12 mb-3">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="card-title">{{$item->title}}</h4>
                                        <h5 class="card-subtitle mb-3">{{$item->excerpt}}</h5>
                                        <p class="card-text">{{$item->content_html}}</p>
                                    </div>
                                    <div class="card-body">
                                        <p class="card-text"> Author: <a href="{{route('post.authors.show',$item->user_id)}}" class="card-link">{{$item->user->name}}</a></p>
                                    </div>
                                    <div class="card-footer d-flex justify-content-between">
                                        <span>Category: <a href="{{route('post.categories.show',$item->category->id)}}" class="card-link">{{$item->category->title}}</a></span>
                                        <span>Published Date: {{$item->published_at}}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="row justify-content-center align-bottom mb-5">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header">Article info</div>
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item">
                                            Category: <a href="{{route('post.categories.show',$item->category->id)}}">{{$item->category->title}}</a>
                                        </li>
                                        <li class="list-group-item">Author: {{$item->user->name}}</li>
                                        <li class="list-group-item">Published date: {{$item->published_at}}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        @include('blog.includes.toplist')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection